module.exports = [
    "Great spot this one, visited last year!",
    "Amazing photo",
    "Great colours in this one",
    "Need to visit here sometime!",
    "Can't wait to go here next year",     
    "Visited this spot a few years ago",     
    "Nailed the composition here",     
    "Beautiful",     
    "Wooooooooowwwww",     
    "What time of year did you take this?",     
    "The edit on this one is great",     
    "Check our my profile I've got a similar shot to this",     
    "You got so lucky with your conditions here",     
    "Perfect conditions",     
    "Thanks for posting this, useful info!",     
    "Great Info",     
    "Nice",     
    "Need to visit this spot soon!",     
    "Never seen this spot before",     
    "Always good to be shown new spots",      
    "Never seen here before ",      
    "Amazing ",      
    "Good Work",      
    "Awesome Spot",      
    "Great time of year to visit",      
    "Sweet",      
    "Lovely!!",      
    "Nailed it",      
    "Interesting angle",      
    "Best one yet",      
    "Best spot I've seen so far",      
    "Never thought of this composition",      
    "Thanks for the info",      
    "Thanks for the details",      
    "Thanks for the spot info",      
    "Thanks for sharing",      
    "Thanks for posting!!",      
    "Beautiful!!",      
    "Impressed!!!!!",      
    "Stunned!!!!!",      
    "Can't wait to see more of your work",      
]