// Gathers all states into one location, easy to change name here instead of at all instances all over the app
export const SET_ALERT ='SET_ALERT';
export const REMOVE_ALERT ='REMOVE_ALERT';
export const REMOVE_ALL_ALERTS ='REMOVE_ALL_ALERTS';
export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_FAIL ='REGISTER_FAIL';
export const USER_LOADED ='USER_LOADED';
export const AUTH_ERROR ='AUTH_ERROR';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAIL ='LOGIN_FAIL';
export const LOGOUT ='LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
export const GET_SEARCH_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";




// Modals
export const OPEN_ADD_EDU_MODAL = 'OPEN_ADD_EDU_MODAL';
export const CLOSE_ADD_EDU_MODAL = 'CLOSE_ADD_EDU_MODAL';
export const OPEN_EDIT_EDU_MODAL = 'OPEN_EDIT_EDU_MODAL';
export const CLOSE_EDIT_EDU_MODAL = 'CLOSE_EDIT_EDU_MODAL';
export const OPEN_ADD_EXP_MODAL = 'OPEN_ADD_EXP_MODAL';
export const CLOSE_ADD_EXP_MODAL = 'CLOSE_ADD_EXP_MODAL';
export const OPEN_EDIT_EXP_MODAL = 'OPEN_EDIT_EXP_MODAL';
export const CLOSE_EDIT_EXP_MODAL = 'CLOSE_EDIT_EXP_MODAL';
export const OPEN_ADD_PROFILE_MODAL = 'OPEN_ADD_PROFILE_MODAL';
export const CLOSE_ADD_PROFILE_MODAL = 'CLOSE_ADD_PROFILE_MODAL';
export const OPEN_EDIT_PROFILE_MODAL = 'OPEN_EDIT_PROFILE_MODAL';
export const CLOSE_EDIT_PROFILE_MODAL = 'CLOSE_EDIT_PROFILE_MODAL';
export const OPEN_EDIT_SOCIALMEDIA_MODAL = 'OPEN_EDIT_SOCIALMEDIA_MODAL';
export const CLOSE_EDIT_SOCIALMEDIA_MODAL = 'CLOSE_EDIT_SOCIALMEDIA_MODAL';
export const OPEN_NEW_POST_MODAL = 'OPEN_NEW_POST_MODAL';
export const CLOSE_NEW_POST_MODAL = 'CLOSE_NEW_POST_MODAL';


